[package]
name = "rgraphparse"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = {version = "0.16.0", features = ["rayon"]}
memmap = "0.7.0"
neo4rs = "0.5.9"
rayon = "1.5.2"
roxmltree = "0.14.1"
tokio = "1.17.0"
tokio-stream = "0.1.8"
zip = { version = "0.6.2", default-features = false, features = ["deflate"] }
